### ISSUE TITLE
希望配置上可以跟强大一些

### ISSUE THREAD

**Issue by crper** [shanquanju/vscode.auto-header#1]
现在用起来感觉很不错；

若是排版上可以再定制下就跟完美了(比如提供多一些占位符变量(`Github,Blog`这些)，类似`time`的`type，format`)，

而创建，编辑，这些依旧

**Comment by shanquanju** [comment]
模版除  [createTime, modifyTime, modifier] 不能变之外，其他字段都是可以通过 [key, value] 来增删的。例如：比如添加 Github, Blog，xxx, aaa, bbb 等等，都是很灵活的。字段的顺序也是可以自己调整的。
"autoHeader": {
    "format": {
        "startWith": "/**",
        "middleWith": "*",
        "endWith": "*/",
        "headerPrefix": "@",
    },
    "header": {
        "Author": "Daniel Lin",
        "Create Time": {
            "type": "createTime",
            "format": "YYYY-MM-DD HH:mm:ss",
        },
        "Modified by": {
            "type": "modifier",
            "value": "Daniel Lin",
        },
        "Modified time": {
            "type": "modifyTime",
            "format": "YYYY-MM-DD HH:mm:ss"
        },
        "Description": "",
        "Github": "https://github.com",
        "Blog": "",
        "xxx": "",
        "aaa": "",
        "bbb" ""
    }
}
不知道这是不是你想要的效果。
